<?php if (!defined('HDPHP_PATH')) exit; 
return array (
  'WATER_ON' => '1',
  'WATER_TEXT' => 'houdunwang.com',
  'WATER_TEXT_SIZE' => '16',
  'WATER_TEXT_COLOR' => '#999999',
  'WATER_IMG' => 'Static/image/water.png',
  'WATER_PCT' => '80',
  'WATER_QUALITY' => '90',
  'WEBNAME' => 'HDPHP框架、HDCMS系统 | 免费、简单的开源产品',
  'ICP' => '京ICP备12048441号-3',
  'HTML_PATH' => 'h',
  'COPYRIGHT' => 'Copyright © 2012-2014  HDPHP&HDCMS来自后盾网 | 国内唯一一家教育机构推出的开源产品',
  'KEYWORDS' => 'php培训,php实训,后盾网',
  'DESCRIPTION' => '后盾网顶尖PHP培训 内容全面 全程实战!业内顶级讲师亲自授课,千余课时独家视频教程免费下载,超百G原创视频资源,实力不容造假!010-64825057',
  'EMAIL' => '2300071698@qq.com',
  'DEFAULT_GROUP' => '5',
  'WEB_OPEN' => '1',
  'UPLOAD_PATH' => 'Upload',
  'ALLOW_TYPE' => 'jpg,jpeg,png,bmp,gif,zip,rar,doc',
  'ALLOW_SIZE' => '10480000',
  'TEL' => '010-64825057',
  'WATER_POS' => '9',
  'DEL_CONTENT_MODEL' => '0',
  'CREATE_INDEX_HTML' => '0',
  'DOWN_REMOTE_PIC' => '0',
  'AUTO_DESC' => '1',
  'AUTO_THUMB' => '0',
  'MEMBER_OPEN' => '1',
  'WEB_CLOSE_MESSAGE' => '网站维护中，请稍候访问...',
  'WEB_STYLE' => 'default',
  'INIT_CREDITS' => '100',
  'CACHE_INDEX' => '-1',
  'CACHE_CATEGORY' => '-1',
  'CACHE_CONTENT' => '-1',
  'REWRITE_ENGINE' => '0',
  'EMAIL_USERNAME' => 'hdcms@houdunwang.com',
  'EMAIL_PASSWORD' => 'admin521',
  'EMAIL_HOST' => 'smtp.exmail.qq.com',
  'EMAIL_PORT' => '25',
  'EMAIL_FROMNAME' => '后盾网',
  'EMAIL_FORMMAIL' => 'hdcms@houdunwang.com',
  'QQ_GROUP' => '166421499',
  'WEIBO' => 'http://www.weibo.com/houdunwang',
);
?>